import numpy as np
import pytest

from neurodb.store import CollectionError, NotFoundError, VectorStore


def test_upsert_and_search(tmp_path):
    store = VectorStore(tmp_path)
    col = store.create_collection("c", 3, "cosine")
    col.upsert(
        [
            {"id": "a", "vector": [1, 0, 0], "metadata": {"k": "a"}},
            {"id": "b", "vector": [0, 1, 0], "metadata": {"k": "b"}},
            {"id": "c", "vector": [1, 1, 0], "metadata": {"k": "c"}},
        ]
    )
    assert col.count == 3
    results = col.search([1, 0, 0], k=2)
    assert len(results) == 2
    assert results[0]["id"] == "a"
    assert results[0]["score"] > results[1]["score"]


def test_autogenerated_ids(tmp_path):
    store = VectorStore(tmp_path)
    col = store.create_collection("c", 2)
    ids = col.upsert([{"vector": [1, 0]}, {"vector": [0, 1]}])
    assert len(ids) == 2
    assert all(isinstance(i, str) and i for i in ids)
    assert col.count == 2


def test_upsert_updates_existing_in_place(tmp_path):
    store = VectorStore(tmp_path)
    col = store.create_collection("c", 2)
    col.upsert([{"id": "x", "vector": [1, 0]}])
    col.upsert([{"id": "x", "vector": [0, 1], "metadata": {"u": 1}}])
    assert col.count == 1
    record = col.get("x")
    assert record["vector"] == [0.0, 1.0]
    assert record["metadata"] == {"u": 1}


def test_dimension_mismatch_raises(tmp_path):
    store = VectorStore(tmp_path)
    col = store.create_collection("c", 3)
    with pytest.raises(CollectionError):
        col.upsert([{"vector": [1, 0]}])


def test_metadata_filter_equality_and_operators(tmp_path):
    store = VectorStore(tmp_path)
    col = store.create_collection("c", 2)
    col.upsert(
        [
            {"id": "1", "vector": [1, 0], "metadata": {"lang": "en", "year": 2020}},
            {"id": "2", "vector": [1, 0], "metadata": {"lang": "de", "year": 2024}},
        ]
    )
    assert [r["id"] for r in col.search([1, 0], k=10, flt={"lang": "de"})] == ["2"]
    assert len(col.search([1, 0], k=10, flt={"lang": {"$in": ["en", "de"]}})) == 2
    assert [r["id"] for r in col.search([1, 0], k=10, flt={"year": {"$gte": 2024}})] == ["2"]


def test_delete(tmp_path):
    store = VectorStore(tmp_path)
    col = store.create_collection("c", 2)
    col.upsert([{"id": "1", "vector": [1, 0]}, {"id": "2", "vector": [0, 1]}])
    assert col.delete(["1"]) == 1
    assert col.count == 1
    with pytest.raises(NotFoundError):
        col.get("1")
    # remaining vector is still searchable and correctly indexed
    assert col.search([0, 1], k=1)[0]["id"] == "2"


def test_persistence_round_trip(tmp_path):
    store = VectorStore(tmp_path)
    col = store.create_collection("docs", 3, "euclidean")
    col.upsert([{"id": "a", "vector": [1, 2, 3], "metadata": {"n": 1}}])
    store.save_all()

    reloaded = VectorStore(tmp_path)
    col2 = reloaded.get_collection("docs")
    assert col2.count == 1
    assert col2.metric == "euclidean"
    assert col2.get("a")["metadata"] == {"n": 1}
    np.testing.assert_allclose(col2.get("a")["vector"], [1, 2, 3])


def test_duplicate_collection_raises(tmp_path):
    store = VectorStore(tmp_path)
    store.create_collection("c", 2)
    with pytest.raises(CollectionError):
        store.create_collection("c", 2)


def test_invalid_collection_name(tmp_path):
    store = VectorStore(tmp_path)
    with pytest.raises(CollectionError):
        store.create_collection("bad name!", 2)


def test_delete_collection_removes_from_disk(tmp_path):
    store = VectorStore(tmp_path)
    store.create_collection("temp", 2)
    assert (tmp_path / "temp").exists()
    store.delete_collection("temp")
    assert not (tmp_path / "temp").exists()
    with pytest.raises(NotFoundError):
        store.get_collection("temp")
